### ISSUE TITLE
SAM headers not found in FASTA

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TranscriptClean#23]
I think I have some idea of how to fix the error message but I wanted to check that I am understanding properly.

I am trying to correct nanopore dRNA reads with splice junctions extracted from mapping Illumina TruSeq reads with STAR against GRCm38.dna.primary.assembly.fa 

Because ensemble FASTA has messy header titles it seems to be causing an issue. Based on the error message below I can clean up the header titles in the primary.assembly file to just include the main part to match the abbreviated headers used in the SAM file? 

```
python TranscriptClean.py --thread 20 --sam /analysisdata/rawseq/fastq/SHARED/000078/Mouse_aging/BAM/all.sam --genome /home/callum/Genome_files/Mus_musculus.GRCm38.dna.primary_assembly.fa --outprefix /home/callum/Mouse_aging/TranscriptClean_output --spliceJns /home/scratch/callum/MM_brain_cDNA_TruSeq_stranded.2ndPassSJ.out.tab
Traceback (most recent call last):
  File "TranscriptClean.py", line 1593, in <module>
    main()
  File "TranscriptClean.py", line 38, in main
    validate_chroms(options.refGenome, options.variantFile, sam_chroms)
  File "TranscriptClean.py", line 468, in validate_chroms
    raise RuntimeError(error_msg)
RuntimeError: One or more SAM chromosomes were not found in the fasta reference.
SAM chromosomes:
{"JH584299.1", "GL456382.1", "JH584295.1", "JH584294.1", "JH584297.1", "1", "GL456360.1", "GL456396.1", "GL456366.1", "14", "GL456212.1", "GL456216.1", "GL456370.1", "12", "GL456379.1", "GL456221.1", "Y", "GL456378.1", "MT", "15", "GL456211.1", "4", "13", "3", "5", "17", "GL456210.1", "JH584293.1", "GL456359.1", "GL456213.1", "7", "JH584296.1", "11", "10", "9", "X", "JH584298.1", "19", "8", "18", "JH584304.1", "2", "GL456350.1", "GL456233.1", "6", "16"}
FASTA chromosomes:
{"GL456239.1 dna:scaffold scaffold:GRCm38:GL456239.1:1:40056:1 REF", "GL456360.1 dna:scaffold scaffold:GRCm38:GL456360.1:1:31704:1 REF", "11 dna:chromosome chromosome:GRCm38:11:1:122082543:1 REF", "JH584295.1 dna:scaffold scaffold:GRCm38:JH584295.1:1:1976:1 REF", "16 dna:chromosome chromosome:GRCm38:16:1:98207768:1 REF", "GL456350.1 dna:scaffold scaffold:GRCm38:GL456350.1:1:227966:1 REF", "JH584292.1 dna:scaffold scaffold:GRCm38:JH584292.1:1:14945:1 REF", "GL456394.1 dna:scaffold scaffold:GRCm38:GL456394.1:1:24323:1 REF", "7 dna:chromosome chromosome:GRCm38:7:1:145441459:1 REF", "JH584297.1 dna:scaffold scaffold:GRCm38:JH584297.1:1:205776:1 REF", "GL456219.1 dna:scaffold scaffold:GRCm38:GL456219.1:1:175968:1 REF", "GL456385.1 dna:scaffold scaffold:GRCm38:GL456385.1:1:35240:1 REF", "2 dna:chromosome chromosome:GRCm38:2:1:182113224:1 REF", "X dna:chromosome chromosome:GRCm38:X:1:171031299:1 REF", "GL456354.1 dna:scaffold scaffold:GRCm38:GL456354.1:1:195993:1 REF", "17 dna:chromosome chromosome:GRCm38:17:1:94987271:1 REF", "GL456221.1 dna:scaffold scaffold:GRCm38:GL456221.1:1:206961:1 REF", "GL456233.1 dna:scaffold scaffold:GRCm38:GL456233.1:1:336933:1 REF", "GL456393.1 dna:scaffold scaffold:GRCm38:GL456393.1:1:55711:1 REF", "GL456213.1 dna:scaffold scaffold:GRCm38:GL456213.1:1:39340:1 REF", "JH584301.1 dna:scaffold scaffold:GRCm38:JH584301.1:1:259875:1 REF", "GL456367.1 dna:scaffold scaffold:GRCm38:GL456367.1:1:42057:1 REF", "GL456382.1 dna:scaffold scaffold:GRCm38:GL456382.1:1:23158:1 REF", "Y dna:chromosome chromosome:GRCm38:Y:1:91744698:1 REF", "6 dna:chromosome chromosome:GRCm38:6:1:149736546:1 REF", "GL456216.1 dna:scaffold scaffold:GRCm38:GL456216.1:1:66673:1 REF", "10 dna:chromosome chromosome:GRCm38:10:1:130694993:1 REF", "12 dna:chromosome chromosome:GRCm38:12:1:120129022:1 REF", "19 dna:chromosome chromosome:GRCm38:19:1:61431566:1 REF", "3 dna:chromosome chromosome:GRCm38:3:1:160039680:1 REF", "4 dna:chromosome chromosome:GRCm38:4:1:156508116:1 REF", "GL456211.1 dna:scaffold scaffold:GRCm38:GL456211.1:1:241735:1 REF", "JH584294.1 dna:scaffold scaffold:GRCm38:JH584294.1:1:191905:1 REF", "GL456210.1 dna:scaffold scaffold:GRCm38:GL456210.1:1:169725:1 REF", "GL456378.1 dna:scaffold scaffold:GRCm38:GL456378.1:1:31602:1 REF", "JH584300.1 dna:scaffold scaffold:GRCm38:JH584300.1:1:182347:1 REF", "GL456372.1 dna:scaffold scaffold:GRCm38:GL456372.1:1:28664:1 REF", "GL456387.1 dna:scaffold scaffold:GRCm38:GL456387.1:1:24685:1 REF", "GL456359.1 dna:scaffold scaffold:GRCm38:GL456359.1:1:22974:1 REF", "GL456368.1 dna:scaffold scaffold:GRCm38:GL456368.1:1:20208:1 REF", "9 dna:chromosome chromosome:GRCm38:9:1:124595110:1 REF", "GL456381.1 dna:scaffold scaffold:GRCm38:GL456381.1:1:25871:1 REF", "GL456212.1 dna:scaffold scaffold:GRCm38:GL456212.1:1:153618:1 REF", "JH584302.1 dna:scaffold scaffold:GRCm38:JH584302.1:1:155838:1 REF", "GL456379.1 dna:scaffold scaffold:GRCm38:GL456379.1:1:72385:1 REF", "JH584298.1 dna:scaffold scaffold:GRCm38:JH584298.1:1:184189:1 REF", "GL456392.1 dna:scaffold scaffold:GRCm38:GL456392.1:1:23629:1 REF", "8 dna:chromosome chromosome:GRCm38:8:1:129401213:1 REF", "JH584299.1 dna:scaffold scaffold:GRCm38:JH584299.1:1:953012:1 REF", "JH584303.1 dna:scaffold scaffold:GRCm38:JH584303.1:1:158099:1 REF", "GL456389.1 dna:scaffold scaffold:GRCm38:GL456389.1:1:28772:1 REF", "5 dna:chromosome chromosome:GRCm38:5:1:151834684:1 REF", "15 dna:chromosome chromosome:GRCm38:15:1:104043685:1 REF", "GL456370.1 dna:scaffold scaffold:GRCm38:GL456370.1:1:26764:1 REF", "14 dna:chromosome chromosome:GRCm38:14:1:124902244:1 REF", "GL456366.1 dna:scaffold scaffold:GRCm38:GL456366.1:1:47073:1 REF", "GL456390.1 dna:scaffold scaffold:GRCm38:GL456390.1:1:24668:1 REF", "1 dna:chromosome chromosome:GRCm38:1:1:195471971:1 REF", "MT dna:chromosome chromosome:GRCm38:MT:1:16299:1 REF", "JH584296.1 dna:scaffold scaffold:GRCm38:JH584296.1:1:199368:1 REF", "JH584304.1 dna:scaffold scaffold:GRCm38:JH584304.1:1:114452:1 REF", "GL456383.1 dna:scaffold scaffold:GRCm38:GL456383.1:1:38659:1 REF", "JH584293.1 dna:scaffold scaffold:GRCm38:JH584293.1:1:207968:1 REF", "18 dna:chromosome chromosome:GRCm38:18:1:90702639:1 REF", "GL456396.1 dna:scaffold scaffold:GRCm38:GL456396.1:1:21240:1 REF", "13 dna:chromosome chromosome:GRCm38:13:1:120421639:1 REF"}
One common cause of this problem is when the fasta headers contain more than one word. If this is the case, try trimming the headers to include only the chromosome name (i.e. '>chr1').
```

**Comment by mei-du** [comment]
trimmed FASTA headers 
` cut -d ' ' -f1 genome.fa `

**Comment by callumparr** [comment]
yeh I used something similar to set up my reference faster. TY
